apiVersion: v1
data:
  mapRoles: |
     - rolearn: arn:aws:iam::515497299016:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-3lvW9hVfSu9l
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
   - userarn: arn:aws:iam::515497299016:user/suresh
      username: suresh
     groups:
      - roboshop-trainee
   - userarn: arn:aws:iam::515497299016:user/ramesh
     username: ramesh
  groups:
      - roboshop-admin

      
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-11T01:49:27Z"
  name: aws-auth
  namespace: kube-system
  uid: a8c9c383-a004-44b1-a2e9-a4b88373c8cd